import{a as m,S as L,i as l}from"./assets/vendor-f736e62a.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))d(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const h of s.addedNodes)h.tagName==="LINK"&&h.rel==="modulepreload"&&d(h)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function d(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();m.defaults.baseURL="https://pixabay.com/api/";async function f(o,t){try{return(await m.get("",{params:{key:"45125391-2052bf46b2b6e76b78c60a950",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}})).data}catch(r){console.log(r)}}function y(o,t){const r=o.hits.map(e=>`
     <li>
        <a class="gallery-link" href=${e.largeImageURL}>
          <img src="${e.webformatURL}" alt="${e.tags}">
          <div>
            <p><span>Likes</span>${e.likes}</p>
            <p><span>Views</span>${e.views}</p>    
            <p><span>Comments</span>${e.comments}</p>
            <p><span>Downloads</span>${e.downloads}</p>
          </div>
        </a>
      </li>`).join("");t.insertAdjacentHTML("beforeend",r),new L(".gallery a",{captionsData:"alt",captionDelay:"250"}).refresh()}class C{constructor(t,r){this.btnElement=t,this.hiddenClass=r}hide(){this.btnElement.classList.add(this.hiddenClass)}show(){this.btnElement.classList.remove(this.hiddenClass)}}class x{constructor(t,r){this.loaderEl=t,this.hideClass=r}hide(){this.loaderEl.classList.add(this.hideClass)}show(){this.loaderEl.classList.remove(this.hideClass)}}const b=document.querySelector(".form"),v=document.querySelector(".input"),u=document.querySelector(".gallery"),E=document.querySelector(".spin-loader"),w=document.querySelector(".load-btn"),c=new C(w,"is-hidden"),n=new x(E,"is-hidden");let a="",g=15,p=0,i=1;c.hide();function S(o){if(o.preventDefault(),i=1,u.innerHTML="",n.show(),a=v.value.trim(),a===""){l.warning({message:"Not value for search",maxWidth:"320px",position:"topRight",messageColor:"white",backgroundColor:"orange"}),n.hide();return}f(a,i).then(t=>{if(p=Math.ceil(t.totalHits/g),n.hide(),console.log(t),t.hits.length===0?l.error({maxWidth:"320px",position:"topRight",messageColor:"white",backgroundColor:"orange",message:"Sorry, there are no images matching your search query. Please try again!"}):(n.hide(),y(t,u)),i<p&&c.show(),t.hits.length<g&&c.hide(),a===""){n.hide();return}}).catch(t=>{console.log(t),l.error({maxWidth:"320px",position:"topRight",messageColor:"white",backgroundColor:"orange",message:"Error of submit button"})}),b.reset()}async function q(){i+=1;try{const o=await f(a,i);y(o,u);const r=document.querySelector(".gallery li").getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"}),i>=p&&(c.hide(),l.warning({message:"We're sorry, but you've reached the end of search results.",maxWidth:"320px",backgroundColor:"orange"}))}catch(o){console.log(o),l.error({maxWidth:"320px",position:"topRight",messageColor:"white",backgroundColor:"orange",message:"Error of load more button"})}}b.addEventListener("submit",S);w.addEventListener("click",async()=>{n.show(),await q(),n.hide()});
//# sourceMappingURL=commonHelpers.js.map
