import{a as m,S as L,i as l}from"./assets/vendor-f736e62a.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))d(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const h of r.addedNodes)h.tagName==="LINK"&&h.rel==="modulepreload"&&d(h)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function d(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();m.defaults.baseURL="https://pixabay.com/api/";async function f(s,t){try{return(await m.get("",{params:{key:"45125391-2052bf46b2b6e76b78c60a950",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}})).data}catch(o){console.log(o)}}function y(s,t){const o=s.hits.map(e=>`
     <li>
        <a class="gallery-link" href=${e.largeImageURL}>
          <img src="${e.webformatURL}" alt="${e.tags}">
          <div>
            <p><span>Likes</span>${e.likes}</p>
            <p><span>Views</span>${e.views}</p>    
            <p><span>Comments</span>${e.comments}</p>
            <p><span>Downloads</span>${e.downloads}</p>
          </div>
        </a>
      </li>`).join("");t.insertAdjacentHTML("beforeend",o),new L(".gallery a",{captionsData:"alt",captionDelay:"250"}).refresh()}class C{constructor(t,o){this.btnElement=t,this.hiddenClass=o}hide(){this.btnElement.classList.add(this.hiddenClass)}show(){this.btnElement.classList.remove(this.hiddenClass)}}class x{constructor(t,o){this.loaderEl=t,this.hideClass=o}hide(){this.loaderEl.classList.add(this.hideClass)}show(){this.loaderEl.classList.remove(this.hideClass)}}const b=document.querySelector(".form"),v=document.querySelector(".input"),u=document.querySelector(".gallery"),E=document.querySelector(".spin-loader"),w=document.querySelector(".load-btn"),c=new C(w,"is-hidden"),n=new x(E,"is-hidden");let i="",g=15,p=0,a=1;c.hide();function S(s){if(s.preventDefault(),a=1,u.innerHTML="",n.show(),i=v.value.trim(),i===""){l.warning({message:"Not value for search",maxWidth:"320px",position:"topRight",messageColor:"white",backgroundColor:"orange"}),n.hide();return}console.log(i),f(i,a).then(t=>{if(p=Math.ceil(t.totalHits/g),n.hide(),console.log(t),t.hits.length===0?l.error({maxWidth:"320px",position:"topRight",messageColor:"white",backgroundColor:"orange",message:"Sorry, there are no images matching your search query. Please try again!"}):(n.hide(),y(t,u)),a<p&&c.show(),t.hits.length<g&&c.hide(),i===""){n.hide();return}}).catch(t=>{console.log(t),l.error({maxWidth:"320px",position:"topRight",messageColor:"white",backgroundColor:"orange",message:"Error"})}),b.reset()}async function q(){a+=1;try{const s=await f(i,a);y(s,u);const o=document.querySelector(".gallery li").getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"}),console.log(o),a>=p&&(c.hide(),l.warning({message:"We're sorry, but you've reached the end of search results.",maxWidth:"320px",backgroundColor:"orange"}))}catch(s){console.log(s)}}b.addEventListener("submit",S);w.addEventListener("click",async()=>{n.show(),await q(),n.hide()});
//# sourceMappingURL=commonHelpers.js.map
